### PR TITLE
Remove standard build setup layout, focus on what's necessary

### PR DESCRIPTION
**Pull request by TWiStErRob**
mavenCentral() is almost equivalent

https://developer.android.com/studio/build/jcenter-migration

### CODE REVIEW

**Comment by StylingAndroid** [comment]
This is not relevant for CL. Cl is obtained from the google() repo and not either maven central nor jcenter. Technically neither of those need to be there for the samples to work. If we remove `jcenter()` we really should remove `mavenCentral()` as well.

**Comment by TWiStErRob** [comment]
@StylingAndroid updated the branch.

I just wanted to remove an outdated reference as:
 * using jcenter() and mavenCentral() together is kind of weird
 * jcenter() is dead (as shown in link) and it is discouraged to use it

Additionally now the PR includes removal of those as the `repositories` context should be enough to figure out where to put it. Left some comments just in case, but happy to remove those too.

**Comment by StylingAndroid** [comment]
LGTM

@rock3r what do you think?

**Review by StylingAndroid — APPROVED** [review]

**Comment by rock3r** [comment]
:shipit:

**Pull request merged**
